apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: mpi-operator
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
